### ISSUE TITLE
Markdown fiddling

### ISSUE THREAD

**Issue by stevecat** [stevecat/table-magic#1]
| Tables | Are | Cool |
|---|:---:|---:|
| col 3 is | right-aligned | $1600 |
| zebra stripes | are neat | $1 |
| zebra stripes | are neat | $1 |
| zebra stripes | are neat | $1 |
| zebra stripes | are neat | $1 |

**Comment by stevecat** [comment]
Fiddling complete.

**Comment by stevecat** [comment]
| Feature | Description | Example |
|---|---|---:|
| Renders markdown | Uses the showdown library to render contents of table cells for you | **Just** *like* ``this`` |
| Escapes quotes | CSV is easier to edit without so only uses them when necessary | It does an "okay" job |
| Preview table matches GitHub style | As closely as possible | Look! |
| Preserves alignment | Between all views | Switch to CSV and back |
| Hasn't caught fire yet | So far | Hurrah |

**Comment by stevierar** [comment]
:cat:
