### ISSUE TITLE
Expose the converter via GitHub Pages

### ISSUE THREAD

**Issue by jbjonesjr** [stevecat/table-magic#10]
[GitHub Pages](https://help.github.com/articles/what-are-github-pages/) is a static website hosting capability built on top of GitHub. This way you could have a live version of the converter on the web, hosted and versioned by GitHub.

Good work so far! :+1:

**Comment by stevecat** [comment]
Hi @jbjonesjr - I was using my stevecat.github.io repo and manually copying over after each update which felt very impractical. You caused me to discover that I could just create a gh-pages branch, it should be a lot simpler now. Thanks!

Every day is a :school: day!

**Comment by jbjonesjr** [comment]
@stevecat Always happy to spread the pages (and markdown) love. I got referred to this the other day, and was really impressed. Really nice tool, and happy to see if get on your pages site (and it's own site :smile: )

cc/ @benbalter as he is my Pages and Markdown guru, he may be interested as well.

**Comment by stevecat** [comment]
Thank you! I enjoy coding little tools and doing this is great for helping me learn the proper GitHub flow. 

Just added HTML conversion too, hurrah!
