### ISSUE TITLE
"Undefined" cell preview freezes

### ISSUE THREAD

**Issue by cmrberry** [stevecat/table-magic#16]
First of all, this is awesome :heart_eyes: It's super useful for stuff like making logs legible, thank you!

I managed to break this on accident with poorly formatted data. To reproduce it, you can use this sample set:

Date, Name, Count
2015-09-29, test/wrong
2015-09-29, test/wrong
2015-09-29, test/ok, 40
2015-09-28, test/ok, 78

Note the missing third column in the first 2 rows of data. 

1. Paste that in the CSV tab
2. Click the Form tab (looks a little wonky with two missing cells
3. Click the Preview tab (two missing cells now say undefined)
4. Try clicking CSV, Markdown, or Form.

Doesn't do anything when you click on those three tabs from preview. The only way to get out of it is to click HTML, which somehow fixes the problem ¯\\\_(ツ)\_/¯

**Comment by stevecat** [comment]
Thank you @cmrberry 

I *think* I've fixed this by adding empty cells to make up for any extra long rows. It messes up the headers a bit but I think that's preferable to smooshing the extra cells into each other.

I've popped the change onto the [live version](http://stevecat.github.io/table-magic/), does that seem correct to you? :smiley_cat:

**Comment by cmrberry** [comment]
:sparkles:! Thanks!
