### ISSUE TITLE
Feature request: paste table data

### ISSUE THREAD

**Issue by erikr** [stevecat/table-magic#31]
Check out https://www.tablesgenerator.com/markdown_tables: file → paste table data.

Would be great to have this feature on table-magic (which has a cleaner UI)!

**Comment by stevecat** [comment]
Hey @erikr! Thanks for opening this. 

I've found that *some* applications, including Chrome, will copy table data as TSV so it's worth copying the table, popping it into the CSV/TSV tab, and seeing if that works. This is actually the reason I added TSV support 😸 

For times when that doesn't work, it looks like it should be possible to add support for pasting from other applications. Browser support might be a bit patchy though.

**Comment by erikr** [comment]
@stevecat Amazing! Confirming copy-paste from Excel to [https://stevecat.net/table-magic](https://stevecat.net/table-magic) works in both Chrome and Safari, at least for the small table I tried.

Thanks for your great work on this!

Consider indicating to the user somewhere that copy-paste in that tab is possible.

Closing issue.
